[project]
name = "pi-cluster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=10.5.0",
    "gpiozero>=2.0.1",
    "psutil>=6.1.0",
    "ruff>=0.7.1",
    "types-psutil>=6.1.0.20241022",
]
